
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[392] =
    {   0,
        0,    0,   60,   60,    0,    0,    0,    0,    0,    0,
        0,    0,   71,   69,   67,   68,   67,   68,   26,   56,
       53,   24,   69,   20,   30,   12,   28,   13,   23,   69,
       14,   55,   55,   32,   22,   11,   17,   53,   53,   21,
       31,   36,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   18,   69,
       29,   60,   57,   57,   58,   60,    3,    2,    2,    7,
        6,    6,    7,   66,   62,   62,   61,   65,    8,   70,
       68,   25,   53,   10,   52,   33,   54,    0,    4,    1,
       54,    0,    0,    0,    0,   55,    0,   34,   19,   15,

       16,   35,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   52,   53,   53,   53,   53,
       53,   53,   53,   53,   42,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   27,   60,   60,   60,   58,   60,
       57,   60,   60,   60,    0,   60,   60,    2,    6,    5,
       62,   64,   63,   54,    0,    0,    0,   54,    0,    0,
       54,   55,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   52,   53,   53,   53,   43,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   60,
       59,   60,    0,    0,   60,   60,    0,   54,    0,   54,
        0,    0,    0,   54,   54,    0,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   41,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   52,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,    9,   50,   53,   53,   60,   60,   58,
       60,   54,    0,    0,    0,   54,   54,    0,   53,   53,
       53,   53,   53,   53,   38,   53,   53,   53,   53,   52,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   52,   53,   53,   51,   59,   60,
        0,   54,    0,   53,   49,   52,   53,   53,   53,   53,
       40,   53,   53,   53,   53,   53,   53,   53,   53,   46,
       47,   48,   53,   53,   53,   53,   60,   39,   52,    0,
       53,   37,   53,   53,   53,   53,   53,   53,   53,   53,
       53,    0,    0,   53,   53,   53,   53,   53,   53,    0,
        0,   53,   53,   53,    0,    0,   53,    0,    0,   53,
        0,    0,    0,    0,    0,    0,    0,    0,   45,   44,
        0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[409] =
    {   0,
        0,    0,   60,   61,   67,   68,   71,   72,   75,   76,
      696,  695,  697,  700,  700,  700,  700,  693,  671,  700,
        0,  700,  683,  700,  700,  700,  678,  700,   65,   67,
       75,   75,   90,  700,   76,  668,   79,  643,   62,  700,
      700,  700,   69,   67,   77,   83,   82,   92,  641,   96,
      640,   98,   96,  649,  100,   98,  638,  644,  700,  624,
      700,  152,  700,  681,  700,  156,  700,  700,  680,  700,
      700,  679,  662,  700,  700,  677,  700,  137,  700,  700,
      700,  700,    0,  700,  700,  700,  142,  640,  700,  700,
      145,  171,  191,  159,  193,  208,  210,  700,  700,  700,

      700,  700,  625,  626,  624,  623,  622,  624,  633,  618,
      118,  635,  634,  620,  627,  612,  613,  610,  610,  616,
      613,  611,  608,  605,    0,  607,  121,  608,  602,  598,
      607,  615,  151,  615,  597,  600,  151,  598,  604,  598,
      124,  180,  176,  602,  700,  243,  700,  641,  700,  247,
      700,  253,  635,  217,  228,  259,  192,  700,  700,  700,
      700,  700,  700,  252,  260,  219,  594,  262,  294,  212,
      272,  296,  602,  597,  586,  585,  598,  590,  600,  595,
      594,  595,  580,  578,  213,  594,  592,  588,  579,  586,
      572,  588,  587,    0,  572,  175,  567,  580,  577,  574,

      570,  570,  559,  560,  566,  557,  559,  556,  565,  568,
      553,  568,  552,  554,  554,  562,  562,  564,  552,  316,
      700,  320,  589,  295,  324,  334,  313,  320,  555,  349,
      341,  332,  324,  343,  358,  369,  554,  546,  554,  541,
      540,  551,  544,  546,  535,  533,  542,  530,  537,    0,
      534,  542,  534,  526,  539,  526,  541,  524,  519,    0,
      538,  537,  532,  527,  518,  515,  524,  529,  514,  527,
      521,  506,  509,    0,    0,  507,  520,  388,  394,  700,
      401,  380,  387,  505,  390,  392,  395,  397,  518,  515,
      508,  519,  500,  517,    0,  503,  504,  510,  510,  501,

      499,  492,  483,  482,  479,  469,  426,  441,  440,  428,
      438,  421,  431,  420,  417,  423,  422,    0,  229,  419,
      422,  413,  417,  412,    0,  443,  423,  410,  403,  403,
        0,  403,  395,  409,  409,  409,  404,  400,  383,    0,
        0,    0,  395,  381,  389,  377,  437,  700,  402,  356,
      345,    0,  355,  338,  345,  343,  336,  322,  319,  311,
      311,  288,  282,  278,  273,  279,  275,  262,  244,  259,
      235,  233,  236,  211,  212,  239,  210,  193,  193,  203,
      164,  131,  150,  105,   98,   86,   48,   44,  700,  700,
      700,  480,  484,  488,  492,  496,   63,  500,  504,  508,

      512,  516,  520,  524,  528,  532,  536,  540
    } ;

static const flex_int16_t yy_def[409] =
    {   0,
      391,    1,  392,  392,  393,  393,  394,  394,  395,  395,
      396,  396,  391,  391,  391,  391,  391,  391,  391,  391,
      397,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  397,  397,  391,
      391,  391,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  391,  391,
      391,  398,  391,  391,  391,  399,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  400,  391,  391,
      391,  391,  397,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  391,  398,  391,  391,  391,  399,
      391,  401,  402,  402,  403,  404,  405,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  401,
      391,  406,  402,  391,  407,  399,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  401,  407,  391,
      406,  391,  391,  391,  391,  391,  391,  391,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  403,  408,
      391,  391,  391,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  407,  391,  397,  391,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  391,  391,  397,  397,  397,  397,  397,  397,  391,
      391,  397,  397,  397,  391,  391,  397,  391,  391,  397,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
        0,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391
    } ;

static const flex_int16_t yy_nxt[763] =
    {   0,
       14,   15,   16,   17,   18,   15,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   21,   21,   38,   39,   40,
       14,   41,   42,   21,   43,   44,   45,   46,   47,   48,
       49,   21,   50,   21,   21,   51,   21,   52,   21,   53,
       54,   55,   56,   21,   57,   58,   21,   21,   21,   59,
       60,   61,   63,   63,   64,   64,   83,   65,   65,   68,
       68,   69,   69,   71,   71,   72,   72,   75,   75,   76,
       76,   85,   77,   77,   73,   73,   87,   87,   89,   86,
       66,   66,   91,   90,   92,   92,  390,   95,   98,   99,

      389,   93,  101,  102,  106,   78,   78,   91,   94,   96,
       96,  111,   88,   93,  104,  108,   93,  109,  112,  105,
      107,  115,  113,   97,  110,  114,  120,  117,   93,  118,
      132,  116,  129,  388,  121,  125,  130,  122,  119,  141,
      123,  136,  126,  127,  163,  387,  133,  386,  142,  134,
       95,  131,  137,  138,  147,  139,  148,  140,  153,  149,
      154,  164,  164,  155,  168,  168,  213,  163,  165,  181,
      182,  169,  197,  198,  214,  166,  163,  385,   92,   92,
      165,  384,  150,  169,  163,  208,  156,  163,   91,  163,
       92,   92,   94,  203,  147,  146,  148,   93,  170,  204,

       95,  209,  383,  146,   94,  170,  146,  170,  146,   93,
      171,  171,  172,  172,  215,   95,  157,   95,  217,  147,
      255,  218,  226,  256,  221,   91,   95,   96,   96,   96,
       96,  171,  171,  216,   93,  149,  149,  194,  164,  164,
      194,   97,  382,   97,  381,  147,   93,  148,  380,  153,
      149,  154,  166,   95,  155,  147,  379,  148,  224,  224,
      221,  153,  378,  154,  246,  247,  149,  227,   95,  377,
       95,  164,  164,  150,  227,  194,  227,  156,  165,  228,
      228,  230,  230,  222,  194,  166,  146,  376,  231,  150,
      165,  235,  235,  375,  146,  232,  194,  146,  146,  146,

      231,  233,  155,   95,  374,  236,  146,  157,  233,  146,
      233,  146,  194,  234,  234,  172,  172,  194,  147,  146,
      148,  373,  153,  221,  154,  155,  147,  221,  148,   95,
      372,  280,  228,  228,  155,  371,  153,  370,  154,  282,
      282,  391,  155,  234,  234,  155,  222,  155,  285,  194,
      222,  230,  230,  283,  281,  285,   95,  285,  369,  220,
      286,  286,  287,  287,  226,  232,  368,  220,  230,  230,
      220,  194,  220,  157,  367,  231,  288,  235,  235,  366,
      220,  157,  232,  365,  157,  364,  157,  231,  235,  235,
      147,  236,  148,  194,  157,  221,  147,  194,  148,  282,

      282,  280,  236,  153,  363,  154,  282,  282,  319,  286,
      286,  322,  322,  283,  287,  287,  287,  287,  222,  362,
      283,  153,  361,  154,  281,  323,  280,  360,  288,  359,
      288,  320,  322,  322,  358,  357,  322,  322,  194,  147,
      279,  148,  194,  356,  280,  355,  323,  354,  279,  281,
      323,  279,  194,  279,  194,  194,  353,  352,  279,  351,
      350,  220,  349,  348,  346,  345,  279,  281,  194,  279,
      344,  279,  194,  343,  342,  341,  340,  339,  338,  279,
       62,   62,   62,   62,   67,   67,   67,   67,   70,   70,
       70,   70,   74,   74,   74,   74,   79,   79,   79,   79,

      146,  146,  146,  146,  152,  152,  152,  152,  162,  337,
      162,  162,  220,  220,  220,  220,  223,  194,  223,  223,
      155,  336,  155,  155,  225,  225,  225,  225,  157,  157,
      335,  157,  278,  278,  278,  278,  279,  279,  279,  279,
      347,  347,  347,  347,  194,  334,  333,  332,  331,  330,
      329,  328,  194,  327,  326,  325,  324,  321,  318,  317,
      316,  315,  314,  313,  194,  312,  311,  194,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  194,  300,
      274,  299,  298,  297,  296,  194,  295,  194,  194,  294,
      293,  292,  291,  290,  289,  284,  221,  277,  276,  275,

      274,  273,  272,  194,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  194,  258,  257,
      194,  254,  253,  252,  251,  194,  250,  249,  248,  245,
      194,  244,  194,  194,  243,  242,  241,  240,  239,  238,
      237,  229,  221,  147,  219,  212,  211,  210,  207,  206,
      205,  202,  201,  194,  200,  199,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      180,  179,  178,  177,  176,  175,  174,  173,  167,  161,
      160,  159,  158,  151,  145,  144,  143,  135,  128,  124,
      103,  100,   85,   84,   82,   81,  391,   80,   80,   13,

      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391
    } ;

static const flex_int16_t yy_chk[763] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,  397,    3,    4,    5,
        6,    5,    6,    7,    8,    7,    8,    9,   10,    9,
       10,   29,    9,   10,    7,    8,   30,   30,   31,   29,
        3,    4,   32,   31,   32,   32,  388,   33,   35,   35,

      387,   32,   37,   37,   43,    9,   10,   33,   32,   33,
       33,   45,   30,   32,   39,   44,   33,   44,   45,   39,
       43,   46,   45,   33,   44,   45,   48,   47,   33,   47,
       53,   46,   52,  386,   48,   50,   52,   48,   47,   56,
       48,   55,   50,   50,   78,  385,   53,  384,   56,   53,
       33,   52,   55,   55,   62,   55,   62,   55,   66,   62,
       66,   87,   87,   66,   91,   91,  141,   78,   87,  111,
      111,   91,  127,  127,  141,   87,   78,  383,   94,   94,
       87,  382,   62,   91,   78,  137,   66,   78,   92,   78,
       92,   92,   94,  133,  157,   66,  157,   92,   93,  133,

       95,  137,  381,   66,   92,   93,   66,   93,   66,   92,
       93,   93,   95,   95,  142,   96,   66,   97,  143,  154,
      196,  143,  157,  196,  154,   96,   95,   96,   96,   97,
       97,  170,  170,  142,   96,  155,  319,  142,  166,  166,
      380,   96,  379,   97,  378,  146,   96,  146,  377,  150,
      146,  150,  166,   95,  150,  152,  376,  152,  155,  319,
      152,  156,  375,  156,  185,  185,  156,  165,   96,  374,
       97,  164,  164,  146,  165,  373,  165,  150,  164,  165,
      165,  168,  168,  152,  372,  164,  150,  371,  168,  156,
      164,  171,  171,  370,  150,  168,  369,  150,  156,  150,

      168,  169,  224,  172,  368,  171,  156,  150,  169,  156,
      169,  156,  367,  169,  169,  172,  172,  366,  220,  156,
      220,  365,  222,  220,  222,  224,  225,  222,  225,  172,
      364,  225,  227,  227,  224,  363,  226,  362,  226,  228,
      228,  226,  224,  233,  233,  224,  220,  224,  231,  361,
      222,  232,  232,  228,  225,  231,  172,  231,  360,  222,
      231,  231,  234,  234,  226,  232,  359,  222,  230,  230,
      222,  358,  222,  226,  357,  230,  234,  235,  235,  356,
      222,  226,  230,  355,  226,  354,  226,  230,  236,  236,
      278,  235,  278,  353,  226,  278,  279,  351,  279,  282,

      282,  279,  236,  281,  350,  281,  283,  283,  281,  285,
      285,  286,  286,  282,  287,  287,  288,  288,  278,  349,
      283,  320,  346,  320,  279,  286,  320,  345,  287,  344,
      288,  281,  322,  322,  343,  339,  323,  323,  338,  347,
      281,  347,  337,  336,  347,  335,  322,  334,  281,  320,
      323,  281,  333,  281,  332,  330,  329,  328,  320,  327,
      326,  281,  324,  321,  317,  316,  320,  347,  315,  320,
      314,  320,  313,  312,  311,  310,  309,  308,  307,  320,
      392,  392,  392,  392,  393,  393,  393,  393,  394,  394,
      394,  394,  395,  395,  395,  395,  396,  396,  396,  396,

      398,  398,  398,  398,  399,  399,  399,  399,  400,  306,
      400,  400,  401,  401,  401,  401,  402,  305,  402,  402,
      403,  304,  403,  403,  404,  404,  404,  404,  405,  405,
      303,  405,  406,  406,  406,  406,  407,  407,  407,  407,
      408,  408,  408,  408,  302,  301,  300,  299,  298,  297,
      296,  294,  293,  292,  291,  290,  289,  284,  277,  276,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  229,  223,  219,  218,  217,

      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      195,  193,  192,  191,  190,  189,  188,  187,  186,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  167,  153,  148,  144,  140,  139,  138,  136,  135,
      134,  132,  131,  130,  129,  128,  126,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      110,  109,  108,  107,  106,  105,  104,  103,   88,   76,
       73,   72,   69,   64,   60,   58,   57,   54,   51,   49,
       38,   36,   27,   23,   19,   18,   13,   12,   11,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    //  Eduardo Carneiro - 2020240332
    //  Ricardo Silva - 2020
    #include "ast.h"
    #include "y.tab.h"

    extern no* raiz;

    int line_num = 1;
    int col_num = 1;
    int start_comment = 1;
    int comment_line = 1;
    int comment_col = 1;
    int start_string = 1;
    int flag_tokens_lex = 0;
    int flag_tree=0;
    int flag_syntactic = 1;
#line 761 "lex.yy.c"

#line 763 "lex.yy.c"

#define INITIAL 0
#define _STRING 1
#define COMMENT1 2
#define COMMENT2 3
#define STRING_ERROR 4
#define EOF_TEST 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "jucompiler.l"


#line 988 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 392 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 700 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "jucompiler.l"
{col_num += yyleng;BEGIN COMMENT1;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 30 "jucompiler.l"
{line_num++;col_num = 1;BEGIN 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "jucompiler.l"
{comment_line = line_num; comment_col = col_num + yyleng;BEGIN COMMENT2;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "jucompiler.l"
{line_num = comment_line; col_num = comment_col + yyleng;BEGIN 0;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 35 "jucompiler.l"
{comment_line++;comment_col = 1;}
	YY_BREAK
case YY_STATE_EOF(COMMENT2):
#line 36 "jucompiler.l"
{comment_col+=yyleng;printf("Line %d, col %d: unterminated comment\n",line_num,col_num);BEGIN EOF_TEST;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{comment_col+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(EOF_TEST):
#line 39 "jucompiler.l"
{return 0;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{BEGIN 0;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{if(flag_tokens_lex) printf("BOOLLIT(%s)\n",yytext);col_num+=yyleng; yylval.id = strdup(yytext);return BOOLLIT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{if(flag_tokens_lex) printf("AND\n");col_num+=yyleng; return AND;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if(flag_tokens_lex) printf("ASSIGN\n");col_num+=yyleng; return ASSIGN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{if(flag_tokens_lex) printf("STAR\n");col_num+=yyleng; return STAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if(flag_tokens_lex) printf("COMMA\n");col_num+=yyleng; return COMMA;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if(flag_tokens_lex) printf("DIV\n");col_num+=yyleng; return DIV;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if(flag_tokens_lex) printf("EQ\n");col_num+=yyleng; return EQ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if(flag_tokens_lex) printf("GE\n");col_num+=yyleng; return GE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(flag_tokens_lex) printf("GT\n");col_num+=yyleng; return GT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(flag_tokens_lex) printf("LBRACE\n");col_num+=yyleng; return LBRACE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(flag_tokens_lex) printf("LE\n");col_num+=yyleng; return LE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(flag_tokens_lex) printf("LPAR\n");col_num+=yyleng; return LPAR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(flag_tokens_lex) printf("LSQ\n");col_num+=yyleng; return LSQ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(flag_tokens_lex) printf("LT\n");col_num+=yyleng; return LT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if(flag_tokens_lex) printf("MINUS\n");col_num+=yyleng; return MINUS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if(flag_tokens_lex) printf("MOD\n");col_num+=yyleng; return MOD;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if(flag_tokens_lex) printf("NE\n");col_num+=yyleng; return NE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(flag_tokens_lex) printf("NOT\n");col_num+=yyleng; return NOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(flag_tokens_lex) printf("OR\n");col_num+=yyleng; return OR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(flag_tokens_lex) printf("PLUS\n");col_num+=yyleng; return PLUS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if(flag_tokens_lex) printf("RBRACE\n");col_num+=yyleng; return RBRACE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if(flag_tokens_lex) printf("RPAR\n");col_num+=yyleng; return RPAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if(flag_tokens_lex) printf("RSQ\n");col_num+=yyleng; return RSQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if(flag_tokens_lex) printf("SEMICOLON\n");col_num+=yyleng; return SEMICOLON;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if(flag_tokens_lex) printf("ARROW\n");col_num+=yyleng; return ARROW;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if(flag_tokens_lex) printf("LSHIFT\n");col_num+=yyleng; return LSHIFT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if(flag_tokens_lex) printf("RSHIFT\n");col_num+=yyleng; return RSHIFT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if(flag_tokens_lex) printf("XOR\n");col_num+=yyleng; return XOR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if(flag_tokens_lex) printf("BOOL\n");col_num+=yyleng; return BOOL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if(flag_tokens_lex) printf("CLASS\n");col_num+=yyleng; return CLASS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{if(flag_tokens_lex) printf("DOTLENGTH\n");col_num+=yyleng; return DOTLENGTH;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if(flag_tokens_lex) printf("DOUBLE\n");col_num+=yyleng; return DOUBLE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{if(flag_tokens_lex) printf("ELSE\n");col_num+=yyleng; return ELSE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{if(flag_tokens_lex) printf("IF\n");col_num+=yyleng; return IF;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if(flag_tokens_lex) printf("INT\n");col_num+=yyleng; return INT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if(flag_tokens_lex) printf("PRINT\n");col_num+=yyleng; return PRINT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if(flag_tokens_lex) printf("PARSEINT\n");col_num+=yyleng; return PARSEINT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if(flag_tokens_lex) printf("PUBLIC\n");col_num+=yyleng; return PUBLIC;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{if(flag_tokens_lex) printf("RETURN\n");col_num+=yyleng; return RETURN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{if(flag_tokens_lex) printf("STATIC\n");col_num+=yyleng; return STATIC;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{if(flag_tokens_lex) printf("STRING\n");col_num+=yyleng; return STRING;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "jucompiler.l"
{if(flag_tokens_lex) printf("VOID\n");col_num+=yyleng; return VOID;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 127 "jucompiler.l"
{if(flag_tokens_lex) printf("WHILE\n");col_num+=yyleng; return WHILE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "jucompiler.l"
{if(flag_tokens_lex) printf("RESERVED(%s)\n",yytext);col_num+=yyleng; return RESERVED;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 131 "jucompiler.l"
{if(flag_tokens_lex) printf("ID(%s)\n",yytext);yylval.id = (char*)strdup(yytext);col_num+=yyleng; return ID;}  
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{if(flag_tokens_lex) printf("REALLIT(%s)\n",yytext);yylval.id = (char*)strdup(yytext);col_num+=yyleng; return REALLIT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 135 "jucompiler.l"
{if(flag_tokens_lex) printf("INTLIT(%s)\n",yytext);yylval.id = (char*)strdup(yytext);col_num+=yyleng; return INTLIT;} 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{col_num+=yyleng;BEGIN STRING;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 140 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line_num,col_num-1);line_num++;col_num=1;BEGIN 0;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 141 "jucompiler.l"
{if(flag_tokens_lex) printf("STRLIT(\"%s)\n",yytext);yylval.id = (char*)strdup(yytext);col_num+=yyleng;BEGIN 0;return STRLIT;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 142 "jucompiler.l"
{start_string = col_num-1;yyless(0);BEGIN STRING_ERROR;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 143 "jucompiler.l"
{start_string = col_num-1;yyless(0);BEGIN STRING_ERROR;}
	YY_BREAK
case YY_STATE_EOF(_STRING):
#line 144 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line_num,start_string);BEGIN EOF_TEST;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 "jucompiler.l"
{col_num=+yyleng;BEGIN 0;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 148 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line_num,start_string);line_num++;col_num=1;BEGIN 0;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line_num,col_num,yytext);col_num+=yyleng;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 151 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line_num,col_num,yytext);col_num+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(STRING_ERROR):
#line 152 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line_num,start_string);col_num=1;BEGIN 0;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 153 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 155 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 157 "jucompiler.l"
{line_num++;col_num = 1;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 159 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n",line_num,col_num,yytext);col_num+=yyleng;BEGIN 0;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 161 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1418 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT1):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 392 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 392 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 391);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 161 "jucompiler.l"


void flag_checker(int argc, char *argv[]) {

    for (int i = 1; i < argc; i++) {
        if (argv[i][0]=='-'){
            if (!strcmp(argv[i], "-t")){ // árvore SÓ?
                flag_tokens_lex=0;
                flag_tree = 1;
                flag_syntactic= 1;
                }
            else if(!strcmp(argv[i], "-e2")){ // só erro sintático e lexical
                flag_tokens_lex=0;
                flag_tree=0;
                flag_syntactic=1;
            }
            else if(!strcmp(argv[i], "-l")){ // só lexical com tokens
                flag_tokens_lex=1;
                flag_tree=0;
                flag_syntactic=0;
            }
            else if(!strcmp(argv[i], "-e1")){ // só lexical sem tokens
                flag_tokens_lex=0;
                flag_tree=0;
                flag_syntactic=0;
            }
            else{
                printf("Undefined flag!\n");
                exit(1);
            }
        }
    }
}

int main(int argc, char *argv[])
{
flag_checker(argc,argv);
/* yylex(); */

if (flag_syntactic){
    yyparse();
}
if (flag_tree){
    printf("===============\nARVORE\n===============\n");
    print_AST(raiz,0);
}
return 0;
}

int yywrap()
{
return 1;
}

void yyerror (char *s) { 
    printf ("Line %d, col %d: %s: %s\n", line_num, col_num, s, yytext );
}
