
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
<<<<<<< Updated upstream
static const flex_int16_t yy_accept[357] =
=======
static const flex_int16_t yy_accept[233] =
>>>>>>> Stashed changes
    {   0,
        0,    0,   59,   59,    0,    0,    0,    0,   68,   66,
       64,   65,   66,   24,   55,   66,   51,   22,   66,   18,
       28,   10,   26,   11,   21,   66,   12,   53,   53,   30,
       20,    9,   15,   51,   51,   19,   29,   34,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
<<<<<<< Updated upstream
       51,   51,   51,   16,   66,   27,   59,   56,   67,   58,
       67,   59,    6,    4,    6,    6,   63,   61,   63,   60,
       63,   65,   23,    0,    0,    0,   51,    8,   50,   31,
        0,    3,    0,    0,    0,   53,    0,   32,   17,   13,
       14,   33,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   50,   51,   51,   51,   51,
       51,   51,   51,   40,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   25,   59,   59,   58,   59,   56,   57,   57,
       57,   57,    4,    5,   61,   62,   54,    0,    2,    0,
        0,    1,   53,    0,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   50,   51,   51,   51,   41,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   57,

       57,   57,   57,   57,   57,   57,   54,    2,    0,    0,
        0,    0,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   39,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   50,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,    7,
       48,   51,   51,    0,    0,   52,   51,   51,   51,   51,
       51,   51,   36,   51,   51,   51,   51,   50,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   50,   51,   51,   49,    0,   52,    0,   51,
       47,   50,   51,   51,   51,   51,   38,   51,   51,   51,

       51,   51,   51,   51,   51,   44,   45,   46,   51,   51,
       51,   51,   37,   50,    0,   51,   35,   51,   51,   51,
       51,   51,   51,   51,   51,   51,    0,    0,   51,   51,
       51,   51,   51,   51,    0,    0,   51,   51,   51,    0,
        0,   51,    0,    0,   51,    0,    0,    0,    0,    0,
        0,    0,    0,   43,   42,    0
=======
       51,   16,   66,   27,   59,   56,   67,   58,   67,   59,
        6,    4,    6,    6,   63,   61,   63,   60,   63,   65,
       23,    0,    0,    0,   51,    8,   50,   31,    0,    3,
        0,    0,    0,    0,    0,   52,   32,   17,   13,   14,
       33,   51,   51,   51,   51,   51,   51,   51,   51,   40,

       51,   51,   51,   51,   51,   51,   51,   51,   25,   59,
       59,   58,   59,   56,   57,   57,   57,    4,    5,   61,
       62,   54,    0,    2,    0,    0,    1,    0,    0,   51,
       51,   51,   51,   51,   51,   51,   51,   41,   51,   51,
       51,   51,   51,   51,   51,   51,   57,   57,   57,   57,
       57,   54,    2,    0,    0,    0,    0,    0,   51,   51,
       51,   51,   51,   51,   39,   51,   50,   51,   51,   51,
       51,    7,   48,   51,   57,    0,    0,   53,   53,    0,
       53,   51,   51,   51,   51,   36,   51,   51,   51,   51,
       51,   49,    0,   51,   47,   50,   51,   38,   44,   51,

       45,   46,   37,   50,    0,   35,   51,    0,    0,   51,
        0,    0,   51,    0,    0,   51,    0,    0,   51,    0,
        0,   51,    0,    0,   51,    0,    0,    0,    0,   43,
       42,    0
>>>>>>> Stashed changes
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   12,    1,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   22,    1,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   28,   27,
       27,   27,   29,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   30,   27,   27,   27,   27,   27,   27,   27,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   45,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    5,
        1,    1,    6,    6,    1,    1,    1,    1,    1,    1,
        5,    5,    1,    1,    1,    1,    5,    5,    5,    5,
<<<<<<< Updated upstream
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        7,    5,    5,    5,    5,    5,    5,    5,    7,    5,
        5,    7,    5,    7,    5,    5,    5,    5,    5,    5,
        8,    6,    8
    } ;

static const flex_int16_t yy_base[370] =
    {   0,
        0,    0,   61,   65,   62,   77,   78,   82,  594,  595,
      595,  595,  590,  567,   96,   64,    0,  595,  579,  595,
      595,  595,  574,  595,   70,  542,   56,  595,   86,  595,
       78,  563,   86,  538,   59,  595,  595,  595,   69,   65,
       83,   85,   62,   93,  536,   90,   96,   98,  545,  102,
      103,  534,  540,  595,  520,  595,  139,  595,  578,  595,
      595,  157,  595,  595,  577,  559,  595,  595,  575,  595,
        0,  595,  595,  164,    0,  562,    0,  595,  595,  595,
      536,  595,  572,  155,  152,  162,  170,  595,  595,  595,
      595,  595,  520,  521,  519,  518,  517,  519,  528,  513,

      126,  530,  529,  515,  522,  507,  508,  506,  512,  509,
      507,  504,  501,    0,  503,  132,  499,  495,  504,  512,
       45,  512,  494,  497,  151,  495,  501,  495,   97,  157,
      155,  499,  595,  205,  595,  595,  215,  595,  207,  534,
      533,  222,  595,  595,  595,  595,  238,  532,    0,  490,
      535,  595,  213,  179,  497,  492,  481,  480,  493,  485,
      495,  490,  489,  490,  475,  473,  141,  489,  487,  483,
      482,  468,  484,  483,    0,  468,  181,  463,  476,  471,
      467,  467,  456,  457,  463,  454,  456,  453,  462,  465,
      450,  465,  449,  451,  451,  459,  459,  461,  449,  230,

      595,  247,  487,  595,  241,  275,  595,    0,  452,  237,
      273,  263,  451,  443,  451,  438,  437,  448,  441,  443,
      432,  430,  439,  427,  434,    0,  431,  439,  431,  423,
      436,  423,  438,  421,  416,    0,  435,  434,  429,  424,
      415,  412,  421,  426,  411,  424,  418,  403,  406,    0,
        0,  404,  417,  402,  239,  271,  415,  412,  405,  416,
      397,  414,    0,  400,  401,  407,  407,  398,  396,  389,
      393,  400,  400,  397,  384,  399,  398,  386,  396,  379,
      389,  379,  377,  385,  384,    0,  384,  282,  287,  374,
        0,  400,  377,  358,  349,  349,    0,  346,  337,  343,

      343,  344,  339,  336,  316,    0,    0,    0,  321,  309,
      315,  281,  595,  307,  275,  269,    0,  281,  271,  279,
      280,  275,  263,  264,  263,  271,  259,  250,  248,  247,
      250,  248,  242,  228,  232,  212,  204,  212,  191,  193,
      217,  189,  169,  153,  149,  142,  123,  135,  110,  103,
       95,   62,   37,  595,  595,  595,  329,  337,  345,  349,
      356,  364,  372,  377,  385,  393,  401,  409,  417
    } ;

static const flex_int16_t yy_def[370] =
    {   0,
      356,    1,  357,  357,  358,  358,  359,  359,  356,  356,
      356,  356,  356,  356,  356,  356,  360,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  360,  360,  356,  356,  356,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  356,  356,  356,  361,  356,  356,  356,
      356,  362,  356,  356,  356,  356,  356,  356,  356,  356,
      363,  356,  356,  356,  364,  356,  360,  356,  356,  356,
      356,  356,  365,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  356,  361,  356,  356,  362,  356,  366,  367,
      367,  368,  356,  356,  356,  356,  356,  364,  369,  356,
      365,  356,  356,  356,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  366,

      356,  368,  367,  356,  366,  368,  356,  369,  356,  356,
      356,  356,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  356,  356,  356,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  356,  356,  356,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  356,  360,  356,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  356,  356,  360,  360,
      360,  360,  360,  360,  356,  356,  360,  360,  360,  356,
      356,  360,  356,  356,  360,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,    0,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356
    } ;

static const flex_int16_t yy_nxt[659] =
=======
        1,    7,    1,    1,    5,    5,    5,    5,    5,    5,
        8,    5,    5,    5,    5,    5,    5,    8,    5,    5,
        8,    5,    8,    5,    5,    5,    5,    7,    6,    7
    } ;

static const flex_int16_t yy_base[246] =
    {   0,
        0,    0,   58,   62,   59,   74,   75,   79,  453,  454,
      454,  454,  449,  426,   93,   61,    0,  454,  438,  454,
      454,  454,  433,  454,   67,  402,   53,   83,   91,  454,
       84,  422,   89,  398,   35,  454,  454,  454,  396,  398,
      394,  396,  405,   75,  386,  385,  398,  384,  385,  386,
      391,  454,  374,  454,  116,  454,  429,  454,  454,  124,
      454,  454,  428,  410,  454,  454,  426,  454,    0,  454,
      454,  131,    0,  413,    0,  454,  454,  454,  387,  454,
      117,  122,  116,  132,  138,  147,  454,  454,  454,  454,
      454,  373,  374,  372,  374,  386,  367,  368,  373,    0,

      363,  358,  363,  109,  361,  342,  348,  345,  454,  168,
      454,  454,  175,  454,  171,  368,  366,  454,  454,  454,
      454,  190,  365,    0,  324,  142,  454,  181,  180,  329,
      319,  302,  306,  296,  310,  280,  267,    0,  271,  270,
      274,  259,  259,  271,  271,  263,  201,  454,  209,  300,
      454,  454,    0,  265,  197,  223,  226,  221,  264,  257,
      264,  263,  249,  254,    0,  258,    0,  252,  244,  242,
      248,    0,    0,  249,  227,  235,  256,  259,  262,  189,
      454,  246,  237,  229,  239,    0,  234,  235,  217,  223,
      231,    0,  225,  214,    0,  236,  205,    0,    0,  212,

        0,    0,  454,  227,  191,    0,  199,  186,  173,  190,
      188,  168,  157,  148,  177,  140,  135,  135,  119,  124,
      107,  110,  112,   87,   76,   58,   55,   47,   33,  454,
      454,  454,  321,  329,  337,  341,  349,  357,  365,  370,
      378,  386,  394,  402,  410
    } ;

static const flex_int16_t yy_def[246] =
    {   0,
      232,    1,  233,  233,  234,  234,  235,  235,  232,  232,
      232,  232,  232,  232,  232,  232,  236,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  236,  236,  232,  232,  232,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  232,  232,  232,  237,  232,  232,  232,  232,  238,
      232,  232,  232,  232,  232,  232,  232,  232,  239,  232,
      232,  232,  240,  232,  236,  232,  232,  232,  232,  232,
      241,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  232,  237,
      232,  232,  238,  232,  242,  243,  243,  232,  232,  232,
      232,  232,  240,  244,  232,  241,  232,  241,  232,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  242,  232,  245,  243,
      232,  232,  244,  232,  232,  232,  232,  232,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  242,  232,  232,  232,  232,  232,
      232,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  232,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  232,  236,  232,  236,  236,  232,  232,  236,
      232,  232,  236,  232,  232,  236,  232,  232,  236,  232,
      232,  236,  232,  232,  236,  232,  232,  232,  232,  232,
      232,    0,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232
    } ;

static const flex_int16_t yy_nxt[515] =
>>>>>>> Stashed changes
    {   0,
       10,   11,   12,   10,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   17,   17,   34,   35,
<<<<<<< Updated upstream
       36,   10,   37,   38,   17,   39,   40,   41,   42,   43,
       44,   45,   17,   46,   17,   17,   17,   17,   47,   17,
       48,   49,   50,   51,   17,   52,   53,   17,   17,   17,
       54,   55,   56,   58,   64,   59,   65,   58,   60,   59,
       82,   75,   60,   61,   61,   83,   66,   61,   61,   64,
       68,   65,   69,   76,   68,   70,   69,   79,  183,   70,
      355,   66,   62,   84,  184,   80,   62,   74,   74,   74,

       74,   88,   89,   74,   85,   96,   86,   86,  107,   71,
       91,   92,   94,   71,   98,  354,   99,   95,  101,  108,
       87,   97,   61,  100,  105,  102,   61,   74,  109,  103,
      114,  117,  104,  120,  106,  118,  110,  115,  116,  111,
      193,  135,  112,  353,  124,  129,  136,   84,  194,  121,
      119,  352,  122,  351,  130,  125,  126,   74,  127,  140,
      128,  141,   84,  350,  136,   74,   74,   74,   74,   84,
      137,  147,  154,  154,  349,  153,  153,   84,  163,  164,
       85,  348,   86,   86,  178,  179,  188,  175,  142,   84,
       86,   86,  195,  222,  223,   74,   87,  134,  197,  210,

      210,  198,  189,  347,   87,  134,  211,  135,  134,  135,
      134,  196,  136,  212,  201,  175,   84,  140,  211,  141,
       84,  346,  136,   84,  140,   74,  141,  231,  345,  201,
      232,   84,  135,  153,  153,  344,  137,  201,  202,   74,
       74,   74,   74,  135,  343,  147,  142,   84,  201,  140,
      342,  141,  175,  206,  201,  134,  175,  210,  210,  256,
      256,  202,  200,  134,  211,  341,  134,  340,  134,   74,
      200,  212,  202,  200,   84,  200,  211,  140,  206,  141,
      255,  175,  201,  210,  210,  339,  175,  200,  255,  175,
      255,  288,  288,  256,  256,  200,  338,  212,  200,   74,

      200,  337,  288,  288,  336,  289,  206,  288,  288,  335,
      175,  334,  333,  175,  332,  200,  289,  331,  330,  329,
      175,  289,  175,  200,  328,  327,  200,  326,  200,   57,
       57,   57,   57,   57,   57,   57,   57,   63,   63,   63,
       63,   63,   63,   63,   63,   67,   67,   67,   67,   67,
       67,   67,   67,   77,  325,   77,  134,  134,  324,  134,
      134,  323,  134,  134,  139,  139,  139,  139,  139,  322,
      139,  139,  146,  146,  146,  175,  146,  148,  175,  321,
      320,  148,  319,  148,  148,  151,  151,  151,  151,  151,
      151,  151,  151,  200,  200,  175,  200,  200,  175,  200,

      200,  203,  175,  318,  203,  203,  317,  203,  203,  205,
      205,  205,  205,  205,  316,  205,  205,  208,  315,  208,
      208,  208,  208,  208,  208,  314,  313,  312,  311,  175,
      310,  175,  309,  308,  307,  306,  305,  304,  303,  175,
      302,  301,  175,  300,  299,  298,  297,  296,  295,  294,
      175,  293,  292,  291,  290,  287,  286,  285,  284,  283,
      282,  281,  175,  280,  279,  175,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  175,  268,  250,  267,
      266,  265,  264,  175,  263,  175,  175,  262,  261,  260,
      259,  258,  257,  254,  204,  253,  252,  251,  250,  249,

      248,  175,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  175,  230,  229,
      228,  227,  226,  225,  224,  221,  175,  220,  175,  175,
      219,  218,  217,  216,  215,  214,  213,  152,  209,  207,
      204,  204,  199,  192,  191,  190,  187,  186,  185,  182,
      181,  175,  180,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  162,  161,  160,  159,
      158,  157,  156,  155,  152,  150,  149,  145,  144,  143,
      138,  133,  132,  131,  123,  113,   93,   90,   81,   79,
       78,   73,   72,  356,    9,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356
    } ;

static const flex_int16_t yy_chk[659] =
=======
       36,   10,   37,   38,   17,   17,   39,   40,   41,   42,
       43,   17,   17,   44,   17,   17,   17,   45,   17,   46,
       47,   48,   49,   17,   50,   51,   17,   52,   53,   54,
       56,   62,   57,   63,   56,   58,   57,   80,   73,   58,
       59,   59,   81,   64,   59,   59,   62,   66,   63,   67,
       74,   66,   68,   67,   77,  231,   68,   93,   64,   60,
       82,   94,   78,   60,   72,   72,   72,   72,   85,  230,

       72,   83,  229,   84,   84,  228,   69,   87,   88,   83,
       69,   86,   86,   90,   91,  100,   59,   82,  111,  127,
       59,  128,  101,  112,   72,   85,  116,  167,  117,   82,
      227,  112,   72,   72,   72,   72,  129,  129,  122,   82,
      226,   82,   84,   84,  127,   85,  128,  113,  225,   85,
       83,   72,   84,   84,   85,  113,   82,  224,   86,   86,
      141,  142,   72,  223,  110,   83,   82,   86,   86,  222,
      111,  110,   85,  111,  110,  112,  110,  116,  148,  117,
       82,   85,  112,  127,  221,  128,  220,  155,  219,   72,
       82,   72,   72,   72,   72,  218,   85,  122,  217,  113,

      156,  157,  149,  111,  155,   85,  113,  158,  148,  181,
      181,  116,  216,  117,  155,  110,  148,  156,  156,  158,
      215,   72,  110,  214,  213,  110,  212,  110,  180,  111,
      155,  155,  149,  177,  148,  211,  180,  210,  155,  209,
      149,  181,  181,  156,  157,  208,  178,  179,   72,  147,
      158,  207,  206,  158,  205,  155,  147,  155,  149,  147,
      177,  147,  158,  177,  204,  158,  177,  203,  202,  177,
      201,  200,  199,  198,  197,  196,  178,  178,  195,  178,
      179,  155,  178,  179,  177,  194,  158,  193,  192,  158,
      177,  191,  190,  177,  189,  188,  177,  172,  158,  187,

      186,  158,  185,  184,  183,  182,  176,  151,  174,  173,
      172,  171,  170,  169,  177,  168,  167,  177,  166,  165,
      177,   55,   55,   55,   55,   55,   55,   55,   55,   61,
       61,   61,   61,   61,   61,   61,   61,   65,   65,   65,
       65,   65,   65,   65,   65,   75,  164,  163,   75,  110,
      110,  162,  110,  110,  161,  110,  110,  115,  115,  115,
      115,  115,  160,  115,  115,  121,  121,  121,  159,  121,
      123,  154,  152,  151,  123,  151,  123,  123,  126,  126,
      126,  126,  126,  126,  126,  126,  147,  147,  146,  147,
      147,  145,  147,  147,  150,  144,  143,  150,  150,  140,

      150,  150,  153,  139,  153,  153,  153,  153,  153,  153,
      175,  175,  175,  175,  175,  138,  175,  175,  137,  136,
      135,  134,  133,  132,  131,  130,  125,  124,  120,  119,
      118,  114,  109,  108,  107,  106,  105,  104,  103,  102,
       99,   98,   97,   96,   95,   92,   89,   79,   77,   76,
       71,   70,  232,    9,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
    } ;

static const flex_int16_t yy_chk[515] =
>>>>>>> Stashed changes
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
<<<<<<< Updated upstream
        1,    1,    1,    3,    5,    3,    5,    4,    3,    4,
       27,   16,    4,    3,    3,   27,    5,    4,    4,    6,
        7,    6,    7,   16,    8,    7,    8,   25,  121,    8,
      353,    6,    3,   29,  121,   25,    4,   15,   15,   15,

       15,   31,   31,   15,   29,   39,   29,   29,   43,    7,
       33,   33,   35,    8,   40,  352,   40,   35,   41,   43,
       29,   39,    3,   40,   42,   41,    4,   15,   44,   41,
       46,   47,   41,   48,   42,   47,   44,   46,   46,   44,
      129,   57,   44,  351,   50,   51,   57,   29,  129,   48,
       47,  350,   48,  349,   51,   50,   50,   15,   50,   62,
       50,   62,   84,  348,   62,   74,   74,   74,   74,   86,
       57,   74,   85,   85,  347,   84,   84,   87,  101,  101,
       86,  346,   86,   86,  116,  116,  125,  345,   62,   84,
       87,   87,  130,  167,  167,   74,   86,   62,  131,  154,

      154,  131,  125,  344,   87,   62,  154,  134,   62,  139,
       62,  130,  134,  154,  139,  130,   84,  137,  154,  137,
      153,  343,  137,   86,  142,   74,  142,  177,  342,  142,
      177,   87,  200,  153,  153,  341,  134,  200,  139,  147,
      147,  147,  147,  205,  340,  147,  137,  153,  205,  202,
      339,  202,  338,  142,  202,  137,  337,  210,  210,  255,
      255,  200,  142,  137,  210,  336,  137,  335,  137,  147,
      142,  210,  205,  142,  153,  142,  210,  206,  202,  206,
      211,  334,  206,  212,  212,  333,  332,  202,  211,  331,
      211,  256,  256,  211,  211,  202,  330,  212,  202,  147,

      202,  329,  288,  288,  328,  256,  206,  289,  289,  327,
      326,  325,  324,  323,  322,  206,  288,  321,  320,  319,
      318,  289,  316,  206,  315,  314,  206,  312,  206,  357,
      357,  357,  357,  357,  357,  357,  357,  358,  358,  358,
      358,  358,  358,  358,  358,  359,  359,  359,  359,  359,
      359,  359,  359,  360,  311,  360,  361,  361,  310,  361,
      361,  309,  361,  361,  362,  362,  362,  362,  362,  305,
      362,  362,  363,  363,  363,  304,  363,  364,  303,  302,
      301,  364,  300,  364,  364,  365,  365,  365,  365,  365,
      365,  365,  365,  366,  366,  299,  366,  366,  298,  366,

      366,  367,  296,  295,  367,  367,  294,  367,  367,  368,
      368,  368,  368,  368,  293,  368,  368,  369,  292,  369,
      369,  369,  369,  369,  369,  290,  287,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  262,
      261,  260,  259,  258,  257,  254,  253,  252,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  209,  203,  199,  198,  197,  196,  195,

      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  176,  174,  173,
      172,  171,  170,  169,  168,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  151,  150,  148,
      141,  140,  132,  128,  127,  126,  124,  123,  122,  120,
      119,  118,  117,  115,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  104,  103,  102,  100,   99,   98,   97,
       96,   95,   94,   93,   83,   81,   76,   69,   66,   65,
       59,   55,   53,   52,   49,   45,   34,   32,   26,   23,
       19,   14,   13,    9,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356
=======
        3,    5,    3,    5,    4,    3,    4,   27,   16,    4,
        3,    3,   27,    5,    4,    4,    6,    7,    6,    7,
       16,    8,    7,    8,   25,  229,    8,   35,    6,    3,
       28,   35,   25,    4,   15,   15,   15,   15,   29,  228,

       15,   28,  227,   28,   28,  226,    7,   31,   31,   29,
        8,   29,   29,   33,   33,   44,    3,   28,   55,   81,
        4,   81,   44,   55,   15,   29,   60,  225,   60,   82,
      224,   60,   72,   72,   72,   72,   83,   83,   72,   84,
      223,   28,   82,   82,  126,   85,  126,   55,  222,   29,
       84,   15,   84,   84,   86,   60,   82,  221,   85,   85,
      104,  104,   72,  220,   60,   86,   84,   86,   86,  219,
      110,   60,   85,  115,   60,  110,   60,  113,  115,  113,
       82,   86,  113,  128,  218,  128,  217,  129,  216,   72,
       84,  122,  122,  122,  122,  215,   85,  122,  214,  110,

      129,  129,  115,  147,  155,   86,  113,  129,  147,  180,
      180,  149,  213,  149,  129,  113,  149,  155,  155,  129,
      212,  122,  113,  211,  210,  113,  209,  113,  158,  175,
      156,  155,  147,  157,  175,  208,  158,  207,  129,  205,
      149,  158,  158,  156,  156,  204,  157,  157,  122,  149,
      156,  200,  197,  157,  196,  155,  149,  156,  175,  149,
      157,  149,  156,  177,  194,  157,  178,  193,  191,  179,
      190,  189,  188,  187,  185,  184,  177,  177,  183,  178,
      178,  156,  179,  179,  157,  182,  178,  176,  174,  179,
      177,  171,  170,  178,  169,  168,  179,  166,  178,  164,

      163,  179,  162,  161,  160,  159,  154,  150,  146,  145,
      144,  143,  142,  141,  177,  140,  139,  178,  137,  136,
      179,  233,  233,  233,  233,  233,  233,  233,  233,  234,
      234,  234,  234,  234,  234,  234,  234,  235,  235,  235,
      235,  235,  235,  235,  235,  236,  135,  134,  236,  237,
      237,  133,  237,  237,  132,  237,  237,  238,  238,  238,
      238,  238,  131,  238,  238,  239,  239,  239,  130,  239,
      240,  125,  123,  117,  240,  116,  240,  240,  241,  241,
      241,  241,  241,  241,  241,  241,  242,  242,  108,  242,
      242,  107,  242,  242,  243,  106,  105,  243,  243,  103,

      243,  243,  244,  102,  244,  244,  244,  244,  244,  244,
      245,  245,  245,  245,  245,  101,  245,  245,   99,   98,
       97,   96,   95,   94,   93,   92,   79,   74,   67,   64,
       63,   57,   53,   51,   50,   49,   48,   47,   46,   45,
       43,   42,   41,   40,   39,   34,   32,   26,   23,   19,
       14,   13,    9,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
>>>>>>> Stashed changes
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    //  Eduardo Carneiro - 2020240332
    //  Ricardo Silva - 2020

    int line_num = 1;
    int col_num = 1;
    int start_comment = 1;
<<<<<<< Updated upstream
#line 712 "lex.yy.c"

#line 714 "lex.yy.c"
=======
#line 642 "lex.yy.c"

#line 644 "lex.yy.c"
>>>>>>> Stashed changes

#define INITIAL 0
#define STRING 1
#define COMMENT 2
#define STRING_ERROR 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 17 "jucompiler.l"


<<<<<<< Updated upstream
#line 937 "lex.yy.c"
=======
#line 867 "lex.yy.c"
>>>>>>> Stashed changes

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
<<<<<<< Updated upstream
				if ( yy_current_state >= 357 )
=======
				if ( yy_current_state >= 233 )
>>>>>>> Stashed changes
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
<<<<<<< Updated upstream
		while ( yy_base[yy_current_state] != 595 );
=======
		while ( yy_base[yy_current_state] != 454 );
>>>>>>> Stashed changes

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 19 "jucompiler.l"
{line_num++;col_num+=yyleng;};
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "jucompiler.l"
{start_comment = line_num; BEGIN COMMENT;col_num+=yyleng;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "jucompiler.l"
{start_comment = line_num; BEGIN COMMENT;col_num+=yyleng;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 22 "jucompiler.l"
{line_num++;col_num = 1;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "jucompiler.l"
{col_num+=yyleng;;BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 24 "jucompiler.l"
{col_num+=yyleng;printf("Line %d, col %d: unterminated comment\n",start_comment,col_num);BEGIN 0;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "jucompiler.l"
{printf("BOOLLIT(%s)\n",yytext);col_num+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "jucompiler.l"
{printf("AND\n");col_num+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "jucompiler.l"
{printf("ASSIGN\n");col_num+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "jucompiler.l"
{printf("STAR\n");col_num+=yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "jucompiler.l"
{printf("COMMA\n");col_num+=yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{printf("DIV\n");col_num+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{printf("EQ\n");col_num+=yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "jucompiler.l"
{printf("GE\n");col_num+=yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{printf("GT\n");col_num+=yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{printf("LBRACE\n");col_num+=yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{printf("LE\n");col_num+=yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{printf("LPAR\n");col_num+=yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{printf("LSQ\n");col_num+=yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{printf("LT\n");col_num+=yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{printf("MINUS\n");col_num+=yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{printf("MOD\n");col_num+=yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{printf("NE\n");col_num+=yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{printf("NOT\n");col_num+=yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{printf("OR\n");col_num+=yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{printf("PLUS\n");col_num+=yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{printf("RBRACE\n");col_num+=yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{printf("RPAR\n");col_num+=yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{printf("RSQ\n");col_num+=yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{printf("SEMICOLON\n");col_num+=yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{printf("ARROW\n");col_num+=yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{printf("LSHIFT\n");col_num+=yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{printf("RSHIFT\n");col_num+=yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{printf("XOR\n");col_num+=yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{printf("BOOL\n");col_num+=yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{printf("CLASS\n");col_num+=yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{printf("DOTLENGTH\n");col_num+=yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{printf("DOUBLE\n");col_num+=yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{printf("ELSE\n");col_num+=yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{printf("IF\n");col_num+=yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{printf("INT\n");col_num+=yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{printf("PRINT\n");col_num+=yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{printf("PARSEINT\n");col_num+=yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{printf("PUBLIC\n");col_num+=yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{printf("RETURN\n");col_num+=yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{printf("STATIC\n");col_num+=yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{printf("STRING\n");col_num+=yyleng;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{printf("VOID\n");col_num+=yyleng;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{printf("WHILE\n");col_num+=yyleng;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{printf("RESERVED(%s)\n",yytext);col_num+=yyleng;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{printf("ID(%s)\n",yytext);}col_num+=yyleng;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "jucompiler.l"
<<<<<<< Updated upstream
{printf("REALLIT\n");col_num+=yyleng;}
=======
{printf("INTLIT(%s)\n",yytext);col_num+=yyleng;}   
>>>>>>> Stashed changes
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{printf("INTLIT(%s)\n",yytext);col_num+=yyleng;}   
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 121 "jucompiler.l"
{printf("STRLIT (%s)\n",yytext);col_num+=yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{col_num+=yyleng;BEGIN STRING;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 124 "jucompiler.l"
{BEGIN STRING_ERROR;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 125 "jucompiler.l"
{yyless(0);BEGIN STRING_ERROR;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 "jucompiler.l"
<<<<<<< Updated upstream
{printf("STRLIT (\"%s)\n",yytext);col_num+=yyleng;BEGIN 0;}
=======
{printf("STRLIT(\"%s)\n",yytext);col_num+=yyleng;BEGIN 0;}
>>>>>>> Stashed changes
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 127 "jucompiler.l"
{yyless(0);BEGIN STRING_ERROR;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "jucompiler.l"
{BEGIN 0;}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 130 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line_num,col_num);line_num++;col_num=1;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 131 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line_num,col_num,yytext);col_num+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(STRING_ERROR):
#line 132 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line_num,col_num);col_num=1;BEGIN 0;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 135 "jucompiler.l"
{col_num+=yyleng;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 137 "jucompiler.l"
{line_num++;col_num = 1;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n",line_num,col_num,yytext);BEGIN 0;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "jucompiler.l"
ECHO;
	YY_BREAK
<<<<<<< Updated upstream
#line 1346 "lex.yy.c"
=======
#line 1276 "lex.yy.c"
>>>>>>> Stashed changes
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
<<<<<<< Updated upstream
			if ( yy_current_state >= 357 )
=======
			if ( yy_current_state >= 233 )
>>>>>>> Stashed changes
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
<<<<<<< Updated upstream
		if ( yy_current_state >= 357 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 356);
=======
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 232);
>>>>>>> Stashed changes

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "jucompiler.l"


int main()
{
yylex();
//printf("\n");
//printf("%d",line_num);
return 0;
}

int yywrap()
{
return 1;
}
